### PR TITLE
fix ReactDOM.findDOMNode(this) return null issue

### PR DESCRIPTION
**Pull request by liudonghua123**

### CODE REVIEW

**Comment by javascriptiscoolpl** [comment]
I don't see any reasons to merge base official branch with Your private custom changes. Demo is working fine and rebuilding without any errors. Also coding with "_" (underscore methods) is not good codding style. If You come across any problems, for sure they can be avoided by "normal" methods (without underscore). Sorry and Good Luck !

**Comment by liudonghua123** [comment]
@javascriptiscoolpl hi, I respect your decision, coding with "_" (underscore methods) is not good codding style.
But when I use this package, I got `ReactDOM.findDOMNode(this) return null ` issue, I searched the internet and found that it is possible to use `findDOMNode`, although it is generally best to use `ref`.
more information
https://reactjs.org/docs/react-dom.html#finddomnode
https://reactjs.org/docs/refs-and-the-dom.html
https://stackoverflow.com/questions/45652903/reactdom-finddomnode-return-null-with-refs

My code is on https://github.com/ynu-python-course/python-courses-show/blob/react-sortable-tree-theme-file-explorer/src/App.js

I think it was maybe the way I use `SimplePDF ` is not directly, but conditional dynamically, so I always got `ReactDOM.findDOMNode(this) return null` problem. This problem has some similarity like https://github.com/facebook/react/issues/4044.

I will write a small example to show this case.

**Comment by wujun4code** [comment]
@liudonghua123  Hi, I finally get you here. Sorry for interrupting you in this issue, But I tried every way to make a touch with you, please take a look at https://github.com/liudonghua123/gatsby-remark-sequence/pull/1. Thanks for your good job with that plugin, but it does not work now, I made a pr, please take a look, Sorry for this way to let you know I am looking for you.

Big sorry and Big thanks for your great works.

**Comment by javascriptiscoolpl** [comment]
If You get `null` from `ReactDOM.findDOMNode` this is probably because incorrect React DOM model. Read again how to create `index.html` file for this package (especially the CSS class name), this may help.

**Pull request closed without merging**
